CREATE TABLE CONTENT_TYPE_FIELD (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	identifier varchar(255) not null,
	name varchar(255) not null,
	type varchar(255) not null
);

insert into CONTENT_TYPE_FIELD (identifier, name, type) values ('name', 'Name', 'Symbol');
insert into CONTENT_TYPE_FIELD (identifier, name, type) values ('text', 'Text', 'Symbol');
